spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_portal_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true  # Removed redundant 'hibernate.' prefix
    database: mysql
  #    database-platform: org.hibernate.dialect.MySQL5Dialect
#
#  spring.mail.host=smtp.xxx.com
#  spring.mail.username=xxx@xxx.com
#  spring.mail.password=xxxxx
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 85b74b5e8f3559
    password: e29c72396f1735
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: testdevMAIL55@gmail.com
#    password: FG45%23123
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

application:
  security:
    jwt:
#      secret-key: Z5KwMOYRkvK8uaGsELeNspCVAbUuct4H
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
